spring.application.name=hirescript-api
server.port=9097
spring.profiles.active=dummy

python.api.base-url=${PYTHON_API_BASE_URL:}
python.api.internal-secret=${PYTHON_API_INTERNAL_SECRET:}

#---
spring.config.activate.on-profile=dummy
spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
  org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration


